name: CI - Unit Tests

on:
  pull_request:
    branches: [ dev, main ]
  push:
    branches: [ dev ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, xdebug
          coverage: xdebug
      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-progress --no-suggest
      - name: Run PHPUnit Unit Tests
        run: ./vendor/bin/phpunit --testsuite="Unit Tests" --configuration=phpunit.xml
      - name: Run PHPUnit Use Case Tests
        run: ./vendor/bin/phpunit --testsuite="Use Tests" --configuration=phpunit.xml